### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by treed593** [zenclabs/deploy#3]
`
? How many Docker containers should be deployed? 1
? How much memory should be allocated to each container (in MB)? 2048
Building Docker image hippocampe-image:latest...
Cannot convert undefined or null to object
`

**Comment by fwouts** [comment]
Thank you for the bug report @treed593!

Which OS are you running? Which version of Docker Engine do you have installed?

**Comment by treed593** [comment]
Version 17.09.1-ce-mac42 (21090)
Channel: stable
3176a6af01

**Comment by fwouts** [comment]
Sorry for the very long delay, I was travelling.

I finally managed to reproduce the bug by removing the "EXPOSE 3000" line in the [example server](https://github.com/zenclabs/deploy/blob/master/example-server/Dockerfile).

Could you try adding an [EXPOSE instruction](https://docs.docker.com/engine/reference/builder/#expose) in your Dockerfile (if that's indeed missing) and let me know if it fixes the issue?

In the meantime, I'll release a new version that complains with a clear error message when the Dockerfile doesn't expose any port.
